---
# tasks file for sa-powershell

  - include: tasks_powershell.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - include: tasks_powershell_rpm.yml
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

