---
# tasks file for sa-d

- name: Powershell | Check if my_package is installed
  command: rpm -q powershell
  register: powershell_check_deb
  become: yes
  failed_when: powershell_check_deb.rc > 1
  changed_when: powershell_check_deb.rc == 1
  tags:
    -powershell

- name: Powershell | download package
  get_url:
    url="https://github.com/PowerShell/PowerShell/releases/download/v{{powershell_version}}/powershell-{{powershell_version}}-1.el7.centos.x86_64.rpm"
    dest="/tmp/powershell.rpm"
  when: powershell_check_deb.rc == 1
  tags:
    -powershell

- name: Powershell | install package
  yum: name="/tmp/powershell.rpm" state="present"
  become: true
  when: powershell_check_deb.rc == 1
  tags:
    -powershell
